/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProxySettingsPopover: typeof import('./src/components/ProxySettingsPopover.vue')['default']
  }
}
