name: Mirror Github to Gitee

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mirror the Github repository to Gitee
        uses: Yikun/hub-mirror-action@v1.5
        with:
          src: github/mwlt/liuyao_desktop_tauri2
          dst: gitee/mwlt/liuyao_desktop_tauri
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          force_update: true
          static_list: "liuyao_desktop_tauri2"
          release: true

  sync-release:
    needs: repo-sync
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v3
        with:
          name: release-assets
          path: release-assets

      - name: Create Gitee Release
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: mwlt/liuyao_desktop_tauri
          branch: main 