name: 同步到 Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 同步到 Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/mwlt
          dst: gitee/mwlt
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_PASSWORD }}
          src_token: ${{ secrets.GITHUB_TOKEN }}
          static_list: "liuyao_desktop_tauri2"
          force_update: true
          debug: true

  sync-release:
    needs: sync
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v3
        with:
          name: release-assets
          path: release-assets

      - name: Create Gitee Release
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: ${{ github.repository_owner }}/liuyao_desktop_tauri2
          branch: main 