name: 同步到 Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git Credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://mwlt:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          echo "https://mwlt:${{ secrets.GITEE_PASSWORD }}@gitee.com" >> ~/.git-credentials
      
      - name: 同步到 Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/mwlt
          dst: gitee/mwlt
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_PASSWORD }}
          static_list: "liuyao_desktop_tauri2"
          force_update: true
          debug: true
          clone_style: "https"
          mappings: "liuyao_desktop_tauri2=>liuyao_desktop_tauri"

  sync-release:
    needs: sync
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v3
        with:
          name: release-assets
          path: release-assets

      - name: Create Gitee Release
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: mwlt/liuyao_desktop_tauri
          branch: main 