name: 同步到 Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || github.token }}
      
      - name: Configure Git and SSH
        run: |
          # 配置 Git 用户信息
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 配置 Git 凭证
          git config --global credential.helper store
          echo "https://mwlt:${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          
          # 配置 Gitee SSH
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          
          # 测试 GitHub HTTPS 访问
          echo "Testing GitHub HTTPS access..."
          git ls-remote https://github.com/mwlt/liuyao_desktop_tauri2.git HEAD || true
          
          # 测试 Gitee SSH 访问
          echo "Testing Gitee SSH access..."
          ssh -T git@gitee.com || true
      
      - name: 同步到 Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/mwlt
          dst: gitee/mwlt
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_PASSWORD }}
          static_list: "liuyao_desktop_tauri2"
          force_update: true
          debug: true
          clone_style: "https"
          mappings: "liuyao_desktop_tauri2=>liuyao_desktop_tauri"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

  sync-release:
    needs: sync
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v3
        with:
          name: release-assets
          path: release-assets

      - name: Create Gitee Release
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: mwlt/liuyao_desktop_tauri
          branch: main 